# Generated by Django 5.2.14 on 2026-06-17 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_venda_cliente_alter_venda_usuario_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='arquivo_instalacao',
            field=models.FileField(blank=True, null=True, upload_to='downloads/', verbose_name='Arquivo para Download'),
        ),
    ]
