# Generated by Django 5.2.14 on 2026-06-21 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_jogo_arquivo_instalacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='link_download',
            field=models.URLField(blank=True, null=True, verbose_name='Link Externo de Download'),
        ),
    ]
