# Generated by Django 5.2.18 on 2026-10-07 21:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_avaliacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação'),
        ),
    ]
