# Generated by Django 5.2.14 on 2026-05-28 02:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('icone', models.CharField(blank=True, default='🎮', max_length=50, verbose_name='Ícone (emoji)')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('preco', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Preço (R$)')),
                ('gratuito', models.BooleanField(default=False, verbose_name='Gratuito')),
                ('destaque', models.BooleanField(default=False, verbose_name='Em Destaque')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='jogos/', verbose_name='Imagem de Capa')),
                ('imagem_url', models.URLField(blank=True, null=True, verbose_name='URL da Imagem (alternativa)')),
                ('desenvolvedor', models.CharField(blank=True, max_length=200, verbose_name='Desenvolvedor')),
                ('ano_lancamento', models.IntegerField(blank=True, null=True, verbose_name='Ano de Lançamento')),
                ('avaliacao', models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='Avaliação (0-5)')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jogos', to='games.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Jogo',
                'verbose_name_plural': 'Jogos',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_adicionado', models.DateTimeField(auto_now_add=True, verbose_name='Data Adicionado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='games.jogo', verbose_name='Jogo')),
            ],
            options={
                'verbose_name': 'Favorito',
                'verbose_name_plural': 'Favoritos',
                'ordering': ['-data_adicionado'],
                'unique_together': {('usuario', 'jogo')},
            },
        ),
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('data_adicionado', models.DateTimeField(auto_now_add=True, verbose_name='Data Adicionado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrinho', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrinho', to='games.jogo', verbose_name='Jogo')),
            ],
            options={
                'verbose_name': 'Item do Carrinho',
                'verbose_name_plural': 'Itens do Carrinho',
                'ordering': ['-data_adicionado'],
                'unique_together': {('usuario', 'jogo')},
            },
        ),
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_compra', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da Compra')),
                ('preco_pago', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Preço Pago')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biblioteca', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biblioteca', to='games.jogo', verbose_name='Jogo')),
            ],
            options={
                'verbose_name': 'Jogo na Biblioteca',
                'verbose_name_plural': 'Jogos na Biblioteca',
                'ordering': ['-data_compra'],
                'unique_together': {('usuario', 'jogo')},
            },
        ),
    ]
